name = "rawkode-link"
main = "src/index.ts"
compatibility_date = "2023-08-01"

workers_dev = false

usage_model = "unbound"

routes = [
  { pattern = "rawkode.community", custom_domain = true },
  { pattern = "rawkode.community/*", zone_name = "rawkode.community" },
  { pattern = "rawkode.link", custom_domain = true },
  { pattern = "rawkode.link/*", zone_name = "rawkode.link" },
  { pattern = "rawkode.live", custom_domain = true },
  { pattern = "rawkode.live/*", zone_name = "rawkode.live" },
]
