version: '3.8'

services:
  postgresql:
    image: postgres:15
    environment:
      POSTGRES_DB: academy
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
    ports:
      - '5432:5432'
    volumes:
      - ../../RawkodeAcademy/projects/rawkode.studio/api/migrations/neon-eu:/migrations
      # - ../../api/migrations/neon-eu:/migrations TODO: change after being merged to monorepo
      - ./scripts/migrate.sh:/docker-entrypoint-initdb.d/migrate.sh
