name = "web-links"
compatibility_date = "2022-01-20"
workers_dev = false
main = "src/index.ts"
routes = [
  { pattern = "rawkode.academy", custom_domain = true },
  { pattern = "rawkode.community", custom_domain = true },
]

[build]
command = "yarn install && yarn run build"
