stages:
  - setup
  - lint
  - build
  - deploy

ensure-never-empty:
  stage: setup
  script:
    - echo "Hello, World!"

include:
  - local: projects/rawkode-academy/web/gitlab-ci.yml
    rules:
      - changes:
          - projects/rawkode-academy/web/**/*
