packages:
  - "./dagger"
  - "./projects/rawkode.cloud/dns"
  - "./projects/rawkode.cloud/google-cloud"
  - "./projects/rawkode.cloud/teleport"
  - "./projects/rawkode.studio"
  - "./projects/rawkode.studio/deploy"
  - "./projects/rawkode.studio/workflows-youtube"
