packages:
  - "./dagger"
  - "./presentations/lets-meet-cdktf-python"
  - "./presentations/cloud-native-2.0"
  - "./projects/ci"
  - "./projects/core-infrastructure/gcp-control-plane"
  - "./projects/core-infrastructure/dns"
  - "./projects/core-infrastructure/kubernetes-platform"
  - "./projects/rawkode.academy/website"
  - "./projects/rawkode.academy/cms"
  - "./projects/rawkode.cloud/tfstate"
  - "./projects/rawkode.community/ics-events"
  - "./projects/rawkode.studio"
  - "./projects/rawkode.studio/content-management/desktop"
  - "./projects/rawkode.studio/deploy"
  - "./projects/rawkode.studio/workflows-youtube"
