version: '3.7'

volumes:
  data: {}

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    env_file:
      - .envrc
    logging:
      driver: none
