project_id = "rawkode.academy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

# Only accept local auth locally
[auth]
enabled = true
site_url = "http://localhost:4321"
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[db.pooler]
enabled = false

[realtime]
enabled = false

[storage]
enabled = false

[inbucket]
enabled = false
