name: "Dagger"

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

env:
  DAGGER_LOG_FORMAT: plain
  DAGGER_CACHE_BASE: main-build

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npm ci

      - name: Dagger
        env:
          FORCE_COLOR: 3
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node --loader ts-node/esm dagger.ts
