name: data-embassy

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - projects/data-embassy/**
  pull_request:
    paths:
      - projects/data-embassy/**
  schedule:
    - cron: "6 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: data-validation
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Validate Blox Data
        id: build
        uses: cueblox/github-action@v0.0.9
        with:
          directory: ./projects/data-embassy

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: github.event_name != 'pull_request'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: github.event_name != 'pull_request'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        name: Docker meta
        uses: docker/metadata-action@v3
        if: github.event_name != 'pull_request'
        with:
          images: |
            ghcr.io/rawkode-academy/rawkode-academy/data-embassy
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v2
        if: github.event_name != 'pull_request'
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
