name: schema.rawkode.academy

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - projects/schema.rawkode.academy/**
  pull_request:
    paths:
      - projects/schema.rawkode.academy/**
  schedule:
    - cron: "6 6 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: schema.rawkode.academy
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          working-directory: ./projects/schema.rawkode.academy
          github-comment: false
